name: Backend CI

on:
  push:
    paths: ["backend/**", ".github/workflows/backend-java.yml"]
  pull_request:
    paths: ["backend/**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'   # thử 17 thay vì 21 nếu gặp lỗi

      - name: Build and run tests
        working-directory: backend
        run: mvn -B clean test
