name: Backend CI

on:
  push:
    paths: ["backend/**", ".github/workflows/backend-java.yml"]
  pull_request:
    paths: ["backend/**"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Build with Maven
        working-directory: backend
        run: mvn -B -DskipTests=false clean verify

